name: Run tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: yarn test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn test
